### ISSUE TITLE
App not being built

### ISSUE THREAD

**Issue by kumarharsh** [electronjs/windows-installer#11]
I'm using 2.0.2 build, but still the release folder is not being created. It seems there is some problem with Jetpack maybe?

Some console.log debugging in the generated files (`lib/index.js`) in the `createWindowsInstaller` function gives this output:

```js
CONTEXT3 0 -> 0
CONTEXT3 0 -> 3
CONTEXT3 3 -> 6
CONTEXT3 13 -> end             
```

which I got by putting this:

```js
console.log('CONTEXT3', _context3.prev, '->', _context3.next);
```

in the generated files in the first line of the function:

```js
174:   ...
175:   return _regenerator2.default.wrap(function _callee3$(_context3) {
176:      console.log('CONTEXT3', _context3.prev, '->', _context3.next);
177:      while (1) {
```

Seems like the control is not going beyond this line:

```js
await jetpack.copyAsync(
    p`${__dirname}/../vendor/Update.exe`,
    p`${appDirectory}/Update.exe`);
```

**Comment by TemaSM** [comment]
I don't sure, but it seems to be, that I have the same issue.
I'm using grunt v 0.4.5
Here is example of my task:
```JavaScript
grunt.registerTask('make_installer', 'Make Squirrel installer for Win32', () => {
     let done = grunt.task.current.async()
     electron_installer.createWindowsInstaller({
       appDirectory: 'Source',
       outputDirectory: 'Releases',
       authors: 'Example Ltd.',
       exe: 'HelloElectron.exe',
       noMsi: true,
       description: APP.description,
       version: APP.version,
       title: APP.productName,
       iconUrl: 'http://example.com/favicon.ico',
       setupIcon: 'favicon.ico',
       //remoteReleases: 'APP.updatesURL'
     }, () => {
       grunt.log.writeln('App: Build done!')
       done(true)
     })
   })
```

**Comment by lukeapage** [comment]
Looks like the task copies update.exe directly into your appDirectory and does not specify the `{overwrite: true}` (https://github.com/szwacz/fs-jetpack#copy)
should be an easy fix? work-around, clean and rebuild your app directory? anyone confirm this is the issue?

**Comment by havenchyk** [comment]
@lukeapage I have the same issue and tried with a clean working directory. I'll try to apply your PR.

**Comment by lukeapage** [comment]
There is another pr to fix path joining that could cause the same issue..

**Comment by havenchyk** [comment]
@lukeapage yep, I've already tried it and still have an error during building the application. I think you're talking about #22
