### ISSUE TITLE
Cannot set appDirectory and outputDirectory to external path out of project root

### ISSUE THREAD

**Issue by Castafiore** [electronjs/windows-installer#13]
I wanna build a windows-installer on my Mac, when I set the appDirectory and outputDirectory to the path out of project root, it prepends automatically the root path of project which is not what I want. So could you tell me how to make it right? Thanks!

**Comment by jkudish** [comment]
I guess this is related to #26

**Comment by havenchyk** [comment]
@Castafiore please, confirm is #22 fixes it. Already merged into master.

**Comment by kevinsawicki** [comment]
@Castafiore can you try upgrading to `2.0.5`?

**Comment by havenchyk** [comment]
@Castafiore please, check it with `2.0.5`, otherwise I'll close the issue.

**Comment by havenchyk** [comment]
Feel free to reopen if you still have this problem.
