### ISSUE TITLE
Path error when building on Windows

### ISSUE THREAD

**Issue by jkudish** [electronjs/windows-installer#26]
I am getting a path error when I try to build on a Windows machine. It seems to be double-including the project path for some reason:

```
Error: Path to copy doesn't exist 
C:\Users\*username*\*appfolder*\Users\*username*\*appfolder*\node_modules\electron-winstaller\vendor\Update.exe]
```

The correct path should be:

```
C:\Users\*username*\*appfolder*\node_modules\electron-winstaller\vendor\Update.exe
```

Where `*username*` is my Windows machine username and `*appfolder*` is the root folder of the app.

**Comment by jkudish** [comment]
My settings are:

```
appDirectory: './release/[name of the app]-win32-x64',
outputDirectory: './release/windows',
````

**Comment by paulcbetts** [comment]
We're working on this bug at the moment, thanks for the repor

**Comment by jkudish** [comment]
:+1:

**Comment by JonathonAshworth** [comment]
Is there a workaround for this?

**Comment by develar** [comment]
@JonathonAshworth Use [electron-builder](https://github.com/loopline-systems/electron-builder) We use our own fork.

**Comment by havenchyk** [comment]
@kevinsawicki can be closed after #22

**Comment by kevinsawicki** [comment]
Closing this out, this should be fixed in `2.0.5` which was just published

**Comment by 93Evolution** [comment]
> ฉันได้รับข้อผิดพลาดเส้นทางเมื่อพยายามสร้างบนเครื่อง Windows ดูเหมือนว่าจะเป็นสองครั้งรวมถึงเส้นทางโครงการด้วยเหตุผลบางอย่าง:
> 
> ```
> Error: Path to copy doesn't exist 
> C:\Users\*username*\*appfolder*\Users\*username*\*appfolder*\node_modules\electron-winstaller\vendor\Update.exe]
> ```
> 
> เส้นทางที่ถูกต้องควรเป็น:
> 
> ```
> C:\Users\*username*\*appfolder*\node_modules\electron-winstaller\vendor\Update.exe
> ```
> 
> `*username*`ชื่อผู้ใช้เครื่อง Windows ของฉันอยู่ที่ไหนและ`*appfolder*`เป็นโฟลเดอร์รูทของแอป
