### ISSUE TITLE
ES6 import of 'electron-winstaller' doesn't work

### ISSUE THREAD

**Issue by tomsiwik** [electronjs/windows-installer#31]
//import winstaller from 'electron-winstaller'; <-- doesn't work
    var winstaller = require('electron-winstaller'); <-- works

Otherwise `createWindowsInstaller` is not visible. I wan't to use ES6 convention, is there a workaround? Not sure if that's a feature request, bug or simply my lack of knowledge. Thanks

**Comment by havenchyk** [comment]
What about `import * from as winstaller from 'electron-winstaller'`?

**Comment by tomsiwik** [comment]
Humm.... didn't think about that. Yeah works.. thanks!
