### ISSUE TITLE
Build fails for applications with deep dependencies

### ISSUE THREAD

**Issue by JonathonAshworth** [electronjs/windows-installer#35]
> Attempting to build package from 'bridge.nuspec'.
> The specified path, file name, or both are too long. The fully qualified file na
me must be less than 260 characters, and the directory name must be less than 24
8 characters.

I'm getting this error when attempting to build my application on Windows. I'm using the latest version of npm, have run npm dedupe to flatten the dependency tree as much as possible, and have put the project directly in the C:\ drive of the system.

What else can be done to fix this?

**Comment by lukeapage** [comment]
I would try running this project with debug set (see the readme) and see exactly what is failing, then we can see what to do about it.

when you say the latest version of npm do you mean npm@3? that will produce flat trees in node_modules unless you import packages dependent on the same package with different versions.. I'd be surprised if that gave you a massive path.

**Comment by havenchyk** [comment]
@JonathonAshworth please check the issue from grunt-electron-installer (and possible solution): https://github.com/atom/grunt-electron-installer/issues/39#issuecomment-137590172

**Comment by havenchyk** [comment]
@JonathonAshworth I'm going to close it. Feel free to reopen if you still experience this problem and provided solution doesn't work for you.
