### ISSUE TITLE
Package not published on npm

### ISSUE THREAD

**Issue by rbkreisberg** [electronjs/windows-installer#4]
Contrary to the README.md instructions, this command fails.
> npm install --save-dev electron-winstaller

Will it be published soon?

**Comment by paulcbetts** [comment]
:soon:

**Comment by astoilkov** [comment]
Do you have any estimation for this? We are currently starting our work on the windows distributable and we would love to use this package.

Any information is highly appreciated. Thanks.

**Comment by havenchyk** [comment]
@astoilkov [you can install it with github](https://docs.npmjs.com/cli/install)

**Comment by paulcbetts** [comment]
@astoilkov This should be out early next week

**Comment by kumarharsh** [comment]
@havenchyk installing from github just gives us coffee files, which then becomes another headache

**Comment by paulcbetts** [comment]
I think we're waiting on #2 to land which needs an @kevinsawicki to review

**Comment by kevinsawicki** [comment]
Fixed by #2, version 2.0.0 is now on npm, https://www.npmjs.com/package/electron-winstaller
