### ISSUE TITLE
Clarify msi vs exe difference

### ISSUE THREAD

**Issue by develar** [electronjs/windows-installer#40]
If I understand correctly 
https://github.com/Squirrel/Squirrel.Windows/blob/master/docs/using/machine-wide-installs.md it means that in most cases msi is not required, right? 

For most of users exe is enough, and, for example, to speed up build `electron-builder` or you can disable msi generation by default. (Also, msi can be generated only on windows).

**Comment by jbleuzen** [comment]
I'm having hard time trying to understand why there is a msi package... It get generated but when I run it, the installer runs and crash silently.

So if it's not working or required why is it generated ?

**Comment by havenchyk** [comment]
@paulcbetts could you please clarify it? /cc @kevinsawicki

**Comment by paulcbetts** [comment]
https://get.slack.help/hc/en-us/articles/212475728-Deploying-Slack-via-Microsoft-Installer sums it up pretty well. 

> If I understand correctly 
https://github.com/Squirrel/Squirrel.Windows/blob/master/docs/using/machine-wide-installs.md it means that in most cases msi is not required, right?

This is correct, if you're not distributing your app to an Enterprise audience, you can totally disable this feature

> I'm having hard time trying to understand why there is a msi package... It get generated but when I run it, the installer runs and crash silently.

Log out and log in again, then bingo bango, your app is there :)

**Comment by develar** [comment]
thanks, I have disabled MSI generation by default.

**Comment by gggin** [comment]
why we need log out and log in ?
why not choose path where to install?
why we cannot generate a normal msi?

**Comment by albertvazquezm** [comment]
Hi,

Even loging out and loging in back again, the app isn't installed and any icon is shown when I install my app using the MSI. When I run the EXE, the app gets installed and icons are created.

What's the problem? Am I missing some step? What can make MSI fail and EXE work?

Thanks.

**Comment by paulcbetts** [comment]
> Even loging out and loging in back again, the app isn't installed and any icon is shown when I install my app using the MSI. When I run the EXE, the app gets installed and icons are created.

You almost certainly uninstalled the normal installer then tried to install the MSI. Delete `%LocalAppData%\YOUR_APP` then install the MSI

**Comment by gopikrishnaA** [comment]
"Delete %LocalAppData%\YOUR_APP then install the MSI." This step is not working. Is this works for anyone?

**Comment by Sunyang730** [comment]
Delete %LocalAppData%\YOUR_APP then install the MSI works for me. Make sure after your installation you log out and log back in.

**Comment by ranganath135** [comment]
> Log out and log in again, then bingo bango, your app is there :)

This works for me, but how can I get the `.msi` installer to run regularly?
