### ISSUE TITLE
Weird "green" dialog in windows 7 64

### ISSUE THREAD

**Issue by marcopiraccini** [electronjs/windows-installer#42]
Hi,
I created an installer for win64 and I run it in Windows 7.
When I run it, a strange "green" dialog appears (see attachments). Probably it should be a dialog saying that the installer it's doing the install (copying the files, etc). But it's weird :)
Did anyone had the same behaviour?
![squirrel](https://cloud.githubusercontent.com/assets/668050/13878100/4809ae26-ed0f-11e5-91ba-92eefef67d50.png)

**Comment by develar** [comment]
Originally posted as https://github.com/loopline-systems/electron-builder/issues/253

**Comment by jbleuzen** [comment]
As far as I know it's a gif while installing or updating in Windows... You can change the gif with the option `loadingGif ` in windows options in you package.json.

Was wondering if put a 1x1 blank gif would be a good practise...

**Comment by marcopiraccini** [comment]
Yes, it's this gif! https://github.com/electronjs/windows-installer/blob/master/resources/install-spinner.gif
It's awful! I though that was something wrong :D
Using my gif it works

**Comment by Luncher** [comment]
I also encountered the same problem, I have to replace the gif file, but it does not install.

**Comment by Luncher** [comment]
Can anyone tell me where I can see an error message?
